// packages/ycloud-solid/src/context.tsx
import { createContext, splitProps, type JSXElement } from 'solid-js';

export const YCloudContext = createContext<{
  size?: number;
  color?: string;
  strokeWidth?: number;
  absoluteStrokeWidth?: boolean;
  class?: string;
}>({
  size: 24,
  color: 'currentColor',
  strokeWidth: 2,
  absoluteStrokeWidth: false,
  class: '',
});

interface YCloudProviderProps {
  children: JSXElement;
  size?: number;
  color?: string;
  strokeWidth?: number;
  absoluteStrokeWidth?: boolean;
  class?: string;
}

export function YCloudProvider(props: YCloudProviderProps) {
  const [value, rest] = splitProps(props, [
    'size',
    'color',
    'strokeWidth',
    'absoluteStrokeWidth',
    'class',
  ]);

  return <YCloudContext.Provider value={value}>{rest.children}</YCloudContext.Provider>;
}

// packages/ycloud-react-native/src/context.ts
import { createContext, createElement, type ReactNode, useContext, useMemo } from 'react';

const YCloudContext = createContext<{
  size?: number;
  color?: string;
  strokeWidth?: number;
  absoluteStrokeWidth?: boolean;
}>({
  size: 24,
  color: 'currentColor',
  strokeWidth: 2,
  absoluteStrokeWidth: false,
});

interface YCloudProviderProps {
  children: ReactNode;
  size?: number;
  color?: string;
  strokeWidth?: number;
  absoluteStrokeWidth?: boolean;
}

export function YCloudProvider({
  children,
  size,
  color,
  strokeWidth,
  absoluteStrokeWidth,
}: YCloudProviderProps) {
  const value = useMemo(
    () => ({
      size,
      color,
      strokeWidth,
      absoluteStrokeWidth,
    }),
    [size, color, strokeWidth, absoluteStrokeWidth],
  );

  return createElement(YCloudContext.Provider, { value }, children);
}

export const useYCloudContext = () => useContext(YCloudContext);
